spring.application.name=SpringBatchProcessing
spring.datasource.url=jdbc:postgresql://localhost:5432/SHAIL_PERSONAL_PRACTICE
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

#schema related

spring.sql.init.mode=always
#tables for batch was not created automatically to create them

spring.batch.jdbc.initialize-schema=always
